on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  pull_and_build:
    runs-on: self-hosted
    steps:
      - name: Install requirements
        run: export COMPOSER_HOME="$HOME/.config/composer" && git pull && composer install
        working-directory: /var/www/notes-api/
