on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  pull_test_generate_api_json:
    runs-on: ubuntu-latest
    steps:
      - name: pull, test, generate api json
        uses: appleboy/ssh-action@master
        with:
          username: root
          host: ${{ secrets.SSH_HOST }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            /root/stophp.sh &&
            cd ${{ vars.WORKING_DIRECTORY }} &&
            git pull &&
            php artisan test &&
            php artisan openapi:generate &&
            /root/starthp.sh
